export const TestimonialData = [
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F03986504-0c8f-4f84-8976-a2ffc642cb3a%252Favatar%3Falt%3Dmedia%26token%3D0b178c83-ee7f-4a61-a704-30ff791465c9&w=48&q=75',
        username:'Pathange Balaji Rao',
        Role:'Ex Product Setu, INDmoney',
        comment:'API for PMs was a quick 1-2 hour read which I found to be the most comprehensive guide which I have ever read about APIs. I especially recommend this ebook for you if you are a PM from a non technical background. This compact read is worth the read for 100% 🚀🚀',
        createdAt:'Feb 25, 2023',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F905e5eda-0a2e-4f87-a59d-1d5059cf584b%252Favatar%3Falt%3Dmedia%26token%3D6ffa7cd8-dda9-4926-b1f4-1527805fc5fe&w=48&q=75',
        username:'Jaishil',
        Role:'Product Manager @ Hike | Ex - Treebo,Gameskraft',
        comment:'I don t generally read e-books but this one on APIs is seems like a great story to consume. Must read for all Product Managers. Please add interview questions on APIs too. Would be really great.',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252Fc8c63d83-e341-4551-87df-93b690141ce0%252Favatar%3Falt%3Dmedia%26token%3D62d5d090-e027-4182-a1da-0a4547f9b22a&w=48&q=75',
        username:'Pradyumna Dinni',
        Role:'Product Manager @ Fyle | Ex - Airtel',
        comment:'Hey Venkatesh, Being a non-tech PM, I was intimireviewDated when people use words such as API, response, endpoint, parameters, etc, and your ebook covered everything and helped me to get an understanding of what they mean. Thank you, and keep writing awesome stuff, in simpler terms :)',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F7666b729-ab3d-49c4-b526-32fea4377ca8%252Favatar%3Falt%3Dmedia%26token%3D2103875c-8042-4e22-ac08-11e14c40d22a&w=48&q=75',
        username:'Sourobh Das',
        Role:'Senior Product Manager at Enparadigm | MDI Gurgaon',
        comment:'Your e-book on APIs was superb. It s not that I didn t know about APIs. I understand them well and as a PM, they are an integral part of my product. However, I always had a tough time explaining it to sales folks and customers in a simple language. More often than not, ended up using the cliched restaurant waiter analogy. Your post simplifies APIs a lot. Perhaps one of the best explanation 101s out there. Keep up the good work!',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252Fbba64a21-1dd2-450c-9002-ae9c7ac5836d%252Favatar%3Falt%3Dmedia%26token%3D15353b47-a8b0-4452-bf7b-f15ec0b57db4&w=48&q=75',
        username:'Anubhav Arun',
        Role:'Product @ Flipkart Group(ANS Commerce)',
        comment:'Being a mechanical engineer; I always got rejected in technical rounds of product management interviews. This e-book gave me so much confidence to learn about technology, APIs and integrations that I grabbed two PM offer letter in less than 25 days. Great job, Venkatesh and Deepak!',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F202a4c98-514e-40d6-8351-e22dab952b7b%252Favatar%3Falt%3Dmedia%26token%3D07113649-a299-4420-bb2d-50b5742a4c24&w=48&q=75',
        username:'Aaditya Srinivasan',
        Role:'Product Manager @ CRED',
        comment:'Just wanted to thank you for your amazing content on the e-book API for Product Managers. I was working on an integration with a client and had to write an API doc, your content helped me learn all of it from scratch :) Hoping to learn more. Kudos!',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F202a4c98-514e-40d6-8351-e22dab952b7b%252Favatar%3Falt%3Dmedia%26token%3D07113649-a299-4420-bb2d-50b5742a4c24&w=48&q=75',
        username:'Sourobh Das',
        Role:'Senior Product Manager at Enparadigm | MDI Gurgaon',
        comment:'Your e-book on APIs was superb. It s not that I didn t know about APIs. I understand them well and as a PM, they are an integral part of my product. However, I always had a tough time explaining it to sales folks and customers in a simple language. More often than not, ended up using the cliched restaurant waiter analogy. Your post simplifies APIs a lot. Perhaps one of the best explanation 101s out there. Keep up the good work!',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F7533b358-037c-45af-9c54-6f894582b8d7%252Favatar%3Falt%3Dmedia%26token%3Da9e1727c-c753-4f1b-8c84-899b45b2127f&w=48&q=75',
        username:'Amrendra Pal',
        Role:'Product Manager @ Flipkart | Ex - Paytm, Udaan, ClearTax | 2x Entrepreneur',
        comment:'I was already well versed with APIs and integrations. This e-book helped me to go through and revise all the concepts. Loved the presentation and how information is presented as a story.',
        createdAt:'',
    },
    {
        profile:'https://www.xplainerr.com/_next/image?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ftestimonialto.appspot.com%2Fo%2Ftestimonials%252F6a3d471d-09a9-4eba-8f21-ae84bfefbe3c%252Favatar%3Falt%3Dmedia%26token%3D16057b5a-6c8e-45d3-a250-2edbd7099d4e&w=48&q=75',
        username:'Abhinav Ghosh',
        Role:'UX Researcher @ Glance, InMobi • Startup operator',
        comment:'One of the things I appreciated most about the book was the thorough coverage of different types of APIs, including REST, SOAP, and GraphQL. The author did a great job of explaining the pros and cons of each type and provided a number of useful strategies for choosing the right API for a given situation. In addition to the technical content, I also appreciated the attention the book paid to non-technical considerations such as API design, documentation, and security. Must read for anyone looking to understand APIs!',
        createdAt:'',
    },
]